version: "3"

services:
    php:
      build: docker/php
      restart: always
      volumes:
        - ./:/app
      depends_on:
        - db
        - mailcatcher
    nginx:
      image: nginx:1.12-alpine
      restart: always
      ports:
        - 80:80
      volumes:
        - ./:/app
        - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      depends_on:
        - php
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_PORT=3306
            - PMA_HOST=db
        restart: always
        depends_on:
            - db
    mailcatcher:
      image: schickling/mailcatcher:latest
      restart: always
      ports:
        - 1080:1080
    db:
      image: mysql:5.7
      restart: always
      volumes:
        - ./.docker-data/db/mysql:/var/lib/mysql
        - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_USER: root 
        MYSQL_ROOT_PASSWORD: root



